spring.datasource.url=your_database_url
spring.datasource.username=your_name
spring.datasource.password=your_password
spring.datasource.driver-class-name=${}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${}

# Message/Mail
spring.mail.host=your_email
spring.mail.port=###
spring.mail.username=your_username
spring.mail.password=your_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true